version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gritum-db-local
    restart: always
    environment:
      POSTGRES_USER: gritum_admin
      POSTGRES_PASSWORD: gritum_password
      POSTGRES_DB: gritum_db_local
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres/data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d

networks:
  default:
    name: gritum-network
